name: seamless_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-essentials
  - r-data.table
  - r-plumber
  - r-limma
  - r-edger
  - r-rtsne
  - r-devtools
  - r-seamless
